apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-kart-orders-sm
  namespace: easy-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-kart-orders-sm #This should be same label
  template:
    metadata:
      labels:
        app: easy-kart-orders-sm #This should be same label
    spec:
      containers:
      - name: easy-kart-orders-sm
        image: pdesaidocker/easy-kart-api-orders-sm:210
        ports:
        - containerPort: 8080 #port defined in image dockerfile
        env:
        - name: ConnectionStrings__AzureServiceBus
          valueFrom:
            configMapKeyRef:
              name: easy-kart-orders-sm-config-map # ConfigMap name
              key: azservicebus         # Key in the ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: easy-kart-orders-sm-service
  namespace: easy-kart
spec:
  selector:
    app: easy-kart-orders-sm #This should be same label
  ports:
    - protocol: TCP
      port: 80 #Other pods in the cluster can connect to this service on port 80
      targetPort: 8080 #port defined in image dockerfile
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easy-kart-orderssm-ingress
  namespace: easy-kart
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: 'true'
    ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: easy-kart.pdtechhub.in
      http:
        paths:
          - path: /orderssm(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: easy-kart-orders-sm-service
                port:
                  number: 80
---